language: python
python:
  - "2.7"
env:
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres
    - DB=postgres MC=1
    #- DB=db2
    #- DB=firebird
    #- DB=oracle using snap-ci for oracle
services:
  - memcached
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - if [ $MC == '1' ]; then pip install -q pylibmc ; fi
before_install:
  - chmod +x ci/before_install.sh
  - chmod +x ci/before_install_${DB}.sh
  - chmod +x ci/before_script_${DB}.sh
  - ci/before_install.sh
  - ci/before_install_${DB}.sh
before_script: ci/before_script_${DB}.sh
# command to run tests
script: coverage run manage.py test
after_success:
  coveralls